sections:
  magento_information:
    display: 'Magento Information'
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          visibility: read_only
          listable: true
          validate:
            - required
      -
        handle: sku
        field:
          input_type: text
          antlers: false
          display: Sku
          type: text
          icon: text
          listable: true
          instructions_position: above
          visibility: read_only
      -
        handle: id
        field:
          input_type: text
          antlers: false
          display: id
          type: text
          icon: text
          listable: hidden
          instructions_position: above
          visibility: read_only
          validate:
            - 'unique_entry_value:{collection},{id},{site}'
      -
        handle: visibility
        field:
          options:
            1: 'Not visible individually'
            2: Catalog
            3: Search
            4: 'Catalog, Search'
          multiple: false
          clearable: false
          searchable: true
          taggable: false
          push_tags: false
          cast_booleans: false
          default: '1'
          display: Visibility
          type: select
          icon: select
          localizable: false
          listable: hidden
          instructions_position: above
          visibility: visible
          always_save: false
  content:
    display: Content
    fields: {  }
title: Products
